### ISSUE TITLE
nanoId 적용

### ISSUE THREAD

**Issue by yoon-bomi** [Pet-Ting/Pet-Ting-Server#15]
## AS-IS
- query string, path param 으로 노출되는 id 를 `auto increment` 로 사용

## TO-BE
- query string, path param 으로 노출되는 id 는 nanoId 로 수정 (`userId`, `productId`, `orderId`, `deliveryId`, `chartId`)
- ~product 는 id 대신 `serial` 사용~ serial 컬럼 제거

참고. @MoveJun

**Comment by MoveJun** [comment]
prodct만 productId대신 serial로 사용하는 이유를 알 수 있을까요?

**Comment by yoon-bomi** [comment]
> prodct만 productId대신 serial로 사용하는 이유를 알 수 있을까요?

`productId` 는 개발적으로 사용하는 id 이고 `serial` 은 추후에 상품을 등록하는 판매자에게 제공하거나, 노출되어도 괜찮을 용도로 생각한거였는데 비슷한 의미가 되어서 그냥 통일해도 될 것 같네요.
